apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}-beat
  labels:
    {{- include "charts.labels" . | nindent 4 }}
    app_component: celery-beat
spec:
  replicas: {{ .Values.celery_beat.replicaCount }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
      app_component: celery-beat
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
        app_component: celery-beat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-celery-beat
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "/resido_dev/beat-entrypoint.sh"]
          envFrom:
          - configMapRef:
              name: {{ include "charts.fullname" . }}
          - configMapRef:
              name: {{ include "charts.fullname" . }}-celery-beat
          # readinessProbe:
          #   exec:
          #     command:
          #     - cat
          #     - /tmp/celery_ready
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            {{- range .Values.secrets }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.celery_beat.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- range .Values.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ include "charts.fullname" $ }}-{{ .name }}
            items:
              {{- range .items }}
              - key: {{ .key }}
                path: {{ .path }}
              {{- end }}
        {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}-worker
  labels:
    {{- include "charts.labels" . | nindent 4 }}
    app_component: celery-worker
spec:
  replicas: {{ .Values.celery_worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
      app_component: celery-worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
        app_component: celery-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-celery-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "/resido_dev/worker-entrypoint.sh"]
          envFrom:
          - configMapRef:
              name: {{ include "charts.fullname" . }}
          - configMapRef:
              name: {{ include "charts.fullname" . }}-celery-worker
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # readinessProbe:
          #   exec:
          #     command:
          #     - cat
          #     - /tmp/celery_ready
          resources:
            {{- toYaml .Values.celery_worker.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.secrets }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- range .Values.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ include "charts.fullname" $ }}-{{ .name }}
            items:
              {{- range .items }}
              - key: {{ .key }}
                path: {{ .path }}
              {{- end }}
        {{- end }}

