apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-celery-worker
data:
  {{- range $k, $v := .Values.celery_worker.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-celery-beat
data:
  {{- range $k, $v := .Values.celery_beat.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
