{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "charts.fullname" $ }}-{{ .name }}
type: Opaque
data:
  {{- range .items }}
  {{ .path }}: {{ .value | b64enc }}
  {{- end }}
---
{{- end }}